import {
  MEASURE_LINES_LAYER_ID,
  MEASURE_POINTS_LAYER_ID,
  UNCLUSTERED_WAVE_BUOYS_LAYER_ID,
  WAVE_BUOYS_CLUSTER_LABEL_LAYER_ID,
  WORLD_LAND_BORDER_LAYER_ID,
  WORLD_LAND_FILL_LAYER_ID,
} from './layerIds';
import { PRODUCT, PRODUCTS } from './products';

//last one is the top layer.
export const LAYERS_ORDER = [
  PRODUCTS[PRODUCT.GSLA_ANOMALY_SEA_LEVELS].layerId,
  PRODUCTS[PRODUCT.AUSTEMP_HEATWAVE_SSTA_MOSAIC].layerId,
  PRODUCTS[PRODUCT.AUSTEMP_HEATWAVE_SST_MOSAIC].layerId,
  PRODUCTS[PRODUCT.AUSTEMP_HEATWAVE_MCS_CATEGORY].layerId,
  PRODUCTS[PRODUCT.GSLA_OCEAN_GEOSTROPHIC_CURRENT].layerId,
  WORLD_LAND_BORDER_LAYER_ID,
  WORLD_LAND_FILL_LAYER_ID,
  PRODUCTS[PRODUCT.WAVE_BUOYS].layerId,
  UNCLUSTERED_WAVE_BUOYS_LAYER_ID,
  WAVE_BUOYS_CLUSTER_LABEL_LAYER_ID,
  MEASURE_LINES_LAYER_ID,
  MEASURE_POINTS_LAYER_ID,
] as const;
