import type { OverlaySource } from '@/constants';
import { sourceIdToProduct } from '@/constants';
import { rasterLegendUrl } from '@/helpers';
import { useQuery } from '@tanstack/react-query';
import { Image } from '../Image';
import { setProductErrorByProduct, useMapUIStore } from '@/store';

type RasterLegendProps = {
  overlaySource: OverlaySource;
  scales: number[];
  label: string;
};

/**
 * Generate color legend and detect erros for products:
 * GSLA_ANOMALY_SEA_LEVELS, SST_ANOMALY_MOSAIC
 *
 * This is to detect if the legend generated by thredds sever can be loaded,
 * if failed, the corresponding product tile images in useOverlayLayer should also fail.
 */
export const RasterLegend = ({ overlaySource, scales, label }: RasterLegendProps) => {
  const date = useMapUIStore(s => s.date);
  const { data: legendUrl } = useQuery({
    queryKey: ['rasterLegendUrl', overlaySource, date],
    queryFn: () => rasterLegendUrl(overlaySource, new Date(date)),
    enabled: !!date,
  });

  const validateProduct = (overlaySource: OverlaySource, v: boolean) => () => {
    setProductErrorByProduct(sourceIdToProduct(overlaySource), v);
  };
  return (
    <div className="w-full">
      <div className="w-full">
        <Image
          src={legendUrl || 'invalid-url'}
          key={`${legendUrl}-raster-legend`}
          alt="Color scale legend"
          width="100%"
          height={12}
          imageClassName="w-full object-cover"
          skeletonHeight={12}
          skeletonWidth="w-full"
          showSkeleton={true}
          loading="eager"
          onError={validateProduct(overlaySource, true)}
          onLoadComplete={validateProduct(overlaySource, false)}
          showErrorIcon={false}
        />
        <div className="w-full flex justify-between text-xs text-black mt-1">
          {scales.map(s => (
            <span key={s + overlaySource + 'legend'}>{s}</span>
          ))}
        </div>
      </div>

      <div className="mt-2 text-black text-sm text-center">
        <span>{label}</span>
      </div>
    </div>
  );
};
