import type { RasterSource } from '@/constants';
import { sourceIdToProduct } from '@/constants';
import { rasterLegendUrl } from '@/helpers';
import { useQuery } from '@tanstack/react-query';
import { Image } from '../Image';
import { setProductErrorByProduct, useMapUIStore } from '@/store';

type RasterLegendProps = {
  rasterSource: RasterSource;
  scales: number[];
  label: string;
  legendHeight?: number;
};

/**
 * Generate color legend and detect erros for products:
 * GSLA_ANOMALY_SEA_LEVELS, SST_ANOMALY_MOSAIC
 *
 * This is to detect if the legend generated by thredds sever can be loaded,
 * if failed, the corresponding product tile images in useRasterLayer should also fail.
 */
export function RasterLegend({ rasterSource, scales, label, legendHeight }: RasterLegendProps) {
  const date = useMapUIStore(s => s.date);

  const { data: legendUrl } = useQuery({
    queryKey: ['rasterLegendUrl', rasterSource, date],
    queryFn: () => rasterLegendUrl(rasterSource, new Date(date)),
    enabled: !!date,
  });
  const validateProduct = (rasterSource: RasterSource, v: boolean) => () => {
    setProductErrorByProduct(sourceIdToProduct(rasterSource), v);
  };
  return (
    <div className="w-full">
      <div className="w-full">
        <Image
          src={legendUrl || 'invalid-url'}
          key={`${legendUrl}-raster-legend`}
          alt="Color scale legend"
          width="100%"
          height={legendHeight ?? 10}
          imageClassName="w-full object-cover"
          skeletonHeight={legendHeight ?? 10}
          skeletonWidth="w-full"
          showSkeleton={true}
          loading="eager"
          onError={validateProduct(rasterSource, true)}
          onLoadComplete={validateProduct(rasterSource, false)}
          showErrorIcon={false}
        />
        <div className="w-full flex justify-between text-xs text-black mt-1">
          {scales.map(s => (
            <span key={s + rasterSource + 'legend'}>{s}</span>
          ))}
        </div>
      </div>

      <div className="mt-2 text-caption text-imos-grey text-center">
        <span>{label}</span>
      </div>
    </div>
  );
}
