import axios from 'axios';
import { queryClient } from '@/config/reactQueryConfig';

export const getThreddsCatalog = async (path: string, date: Date): Promise<string> => {
  const year = date.getFullYear();
  const catalogUrl = `/thredds/catalog/${path}/${year}/catalog.html`;

  // Cache catalog fetches to avoid redundant HTTP requests
  return queryClient.fetchQuery({
    queryKey: ['thredds-catalog', path, year],
    queryFn: async () => {
      const catalog = await axios.get<string>(catalogUrl);
      return catalog.data;
    },
  });
};
//TODO: make tile files generated by thredds cache with proper cache control headers. It is better to set caching at server side. Set on cloudfront distribution is not ideal, even it works.
// workaround: Fix CloudFront Cache Behavior. Add caching at the CloudFront distribution level: Cache-Control: public, max-age=86400  (24 hours)

//Current performance issue: when switching dates, gsla layer is quick to update, but sst-anom-mosaic layer is slow to update.

// Reason analysis: gsla layer has pre-generated tiles for more dates and cached in thredds server. But sst not.

// Posible solution:
// 1. pre-generate more tiles for sst-anom-mosaic layer and cache them in thredds server.
// 2. make sure the cache control headers are properly set for tile files in thredds server, so that cloudfront can cache them and serve faster, and clientside browser can also cache them.
